build(node): update node version to 18
pagopa/pagopa-functions-checkout pull request #36
Opened 2023-04-27 13:26 UTC by giovanniberti

#### List of Changes

* update node version to 18

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-04-28 13:50 UTC, infantesimone requested changes
to update
- https://github.com/pagopa/pagopa-functions-checkout/blob/main/.nvmrc
- https://github.com/pagopa/pagopa-functions-checkout/blob/main/.node-version

2023-05-02 08:02 UTC, pietro-tota approved these changes

2023-05-02 08:03 UTC, pietro-tota commented on docker/functions/Dockerfile
> +FROM node:18.0
Sorry, I didn't see @infantesimone comment 😄

2023-05-02 09:35 UTC, giovanniberti commented on docker/functions/Dockerfile
> +FROM node:18.0
Solved with push on 794ac00

2023-05-02 12:31 UTC, infantesimone approved these changes

2023-05-02 12:31 UTC, merged